# Generated by Django 2.2.dev20180812014849 on 2018-08-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.SmallIntegerField(default=0)),
                ('hostname', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
                ('filesystem', models.CharField(max_length=200)),
                ('threshold', models.SmallIntegerField(default=5)),
                ('autoaction', models.BooleanField(default=False)),
            ],
        ),
    ]
