# Generated by Django 2.2.dev20180812014849 on 2018-08-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.SmallIntegerField(default=0)),
                ('url', models.CharField(max_length=300)),
                ('response_code', models.CharField(max_length=10)),
                ('timeout', models.SmallIntegerField(default=60)),
                ('category', models.CharField(max_length=30)),
                ('frequency', models.SmallIntegerField(default=60)),
            ],
        ),
        migrations.RenameModel(
            old_name='Machine',
            new_name='FSList',
        ),
    ]
